### ISSUE TITLE
Mapy.cz map layers does not work

### ISSUE THREAD

**Issue by sveckarel** [liskin/strava-map-switcher#16]
Mapy.cz has new API and restrict access that has been used so far. See https://napoveda.seznam.cz/forum/threads/168947/1

**Comment by liskin** [comment]
Thanks for the link! I'll try to contact them.

**Comment by janjensik** [comment]
Any progress?

**Comment by liskin** [comment]
Yes, some, but just bad news. They won't give us an API key even if we paid them, so we'll need to hack around it somehow and hope they don't notice and send the lawyers. Faking the Referrer is one solution that can be implemented here, or perhaps look at how https://github.com/softopus-io/react-mapycz does it because that works without an API key too. I've been fairly busy lately so I haven't had time to actually implement either.
